name: Auto Merge and Sync to Company

on:
  push:
    branches:
      - "dev_*"

permissions:
  contents: write

jobs:
  merge-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Team Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch All Branches
        run: git fetch origin

      - name: Merge Developer Branch into Development
        run: |
          git checkout development
          git pull origin development
          git merge origin/${{ github.ref_name }} --no-edit
          git push origin development

      - name: Check COMPANY_PAT
        run: |
          if [ -z "${{ secrets.COMPANY_PAT }}" ]; then
            echo "PAT is EMPTY"
            exit 1
          else
            echo "PAT Loaded Successfully"
          fi

      - name: Sync Development to Company Repository
        env:
          COMPANY_PAT: ${{ secrets.COMPANY_PAT }}
        run: |
          git remote remove company || true
          git remote add company https://x-access-token:${COMPANY_PAT}@github.com/harshal5478/cubeage_DevOps_Demo.git
          git push company development